### ISSUE TITLE
VS/Fliesen im Bad

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#11]
Hallo,

wir haben eine Frage zur Vorsatzschale. 
Reicht es aus, die Oberfläche der VS in Fliesen darzustellen oder soll zusätzlich eine weitere Schicht Fliesen verlegt werden. ( Siehe Bild)

![Profilwand ohne Fliesen](https://user-images.githubusercontent.com/90615362/133239482-a23a876f-aef9-4a9b-88e9-d10fbf0a889f.JPG)
Ohne weitere Schicht
(Oberfläche in Fliesen Weiß)

![Profilwand](https://user-images.githubusercontent.com/90615362/133239165-4d28b15e-96df-41d3-94bf-9b0aeb3cd829.JPG)
Mit extra Schicht

**Comment by chb-mort** [comment]
Hallo!
Vielen Dank für den Hinweis. 👍 
Tatsächlich ist das Problem schon beseitigt und in der neuen Version des Templates werden die Fliesen Teil der Vorsatzschale sein.
Bis dahin bitte mit der zweiten Variante arbeiten.
Prinzipiell sollte die reine Oberflächendarstellung nicht zur Definition des Materials genutzt werden.

(Bitte im Beispiel auch darauf achten Fußbodenaufbau und Deckenplatte zu trennen sowie die Fliesen nicht hinter der Vorsatzschale zu "verlegen")
