### ISSUE TITLE
Raumstempel

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#12]
![Raumstempel aktualisieren mit VS](https://user-images.githubusercontent.com/90615362/133457765-113c1866-4601-49cf-b78f-c64689373be8.PNG)

Wir habe ein Problem mit der Aktualisierung der Raumstempel.
Im Bad verschiebt sich der Raumstempel beim aktualisieren vor die Vorsatzschale.
Wie sollen wir mit der Situation um gehen?

**Comment by chb-mort** [comment]
Wenn Sie vermeiden möchten, dass Elemente Einfluss auf die Raumbegrenzung nehmen, gehen Sie in die Elementeigenschaften und wählen danach folgende Option:

![grafik](https://user-images.githubusercontent.com/85555496/133630927-b44882d0-77cb-45c5-a60a-4459090890d5.png)
