### ISSUE TITLE
Absprache: Strichpunktlinie 

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#16]
Wie mit Herrn Ort abgesprochen, legen wir ab sofort die Strichpunktlinie auf die Ebene "98 Gebäudeachsen".

**Comment by chb-mort** [comment]
Issues bitte nur für Problembeschreibungen nutzen.
Absprachen können wir am besten in eine gesonderte Diskussion übernehmen.
