### ISSUE TITLE
Balkontür: Öffnungswinkel

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#18]
![Öffnungswinkel Balkontür DKF Ebene](https://user-images.githubusercontent.com/90615362/134000029-663a9243-d577-48aa-9c73-8cdae26df19c.PNG)
Bei der Balkontür (DK-Fenster) kann kein Öffnungswinkel dargestellt werden. Aufgrund dessen, haben wir die Öffnungswinkel mit 2D-Elementen gezeichnet (Linie). Diese haben wir auf die im Bild markierte Ebene gelegt (siehe Bild). Sind Sie damit einverstanden oder haben Sie einen anderen Lösungsvorschlag?

**Comment by chb-mort** [comment]
Die Linienzeichnung ist für den aktuellen Stand in Ordnung, wir suchen auch noch nach einer Lösung für die korrekte Darstellung über ein Objekt. Das Fenster dann bis dahin über die Klassifizierung als Tür kennzeichnen.

Zur Ebene:
Im nächsten Release werden wir eine neue Ebene mit dem Namen `"00 2D-Elemente"` anlegen.
Diese dann bitte benutzen. Sie können diese auch jetzt schon anlegen.
