### ISSUE TITLE
Vorsatzschale-Etikett

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#20]
Wir hätten gerne ein Etikett für die Vorsatzschalen. In der Wohnung Wansdorfer Steig 12 haben wir das Etikett manuell geändert, da wir die Vorsatzschale aus Einzelteilen zusammengebaut haben. In der neuen Vorlage soll die Vorsatzschale (Profilwand in Höhe und Breite veränderbar) automatisch etikettiert werden können (VS #Maximale Höhe der Wand). Können Sie bitte so ein Etikett hinzufügen?

**Comment by chb-mort** [comment]
Ist als "Etikett Vorsatzschale" angelegt.
