### ISSUE TITLE
Problem Fliesendarstellung

### ISSUE THREAD

**Issue by WA-FPR** [chb-mort/Charlotte-Standard#21]
Im Bad mit ebenerdiger Dusche habe wir zwei unterschiedliche Fliesenarten, die im Grundriss dargestellt wurden.
Das haben wir vorher, durch eine Schraffur die von der Decke (Fußbodenaufbau) dargestellt wurde, gelöst.
In Ihrer Vorlage ist die Schraffur im Raumstempel. Wie sollen wir jetzt die unterschiedlichen Fliesen im Grundriss darstellen?

![Problem Fliesendarstellung](https://user-images.githubusercontent.com/90615362/134182384-052dab0b-4794-4c72-9cfb-f9f78085fd9d.PNG)

(Alte Darstellung der Fliesen im Bad)

**Comment by chb-mort** [comment]
Wir schauen uns die Sache an. 
Vermutlich ergibt die Schraffur auf zwei unterschiedlichen Bodenaufbauten tatsächlich am meisten Sinn.

Welche Lösung würden Sie vorschlagen?

**Comment by chb-mort** [comment]
Wie telefonisch am 28.09.2021 besprochen, bitte **vorläufig** wie folgt vorgehen:
- keine Darstellung der Schraffur via Raumstempel mehr
- für Dusche und Bad unterschiedliche Fußbodenaufbauten (Decken) benutzen
- die 2D-Deckschraffur des Fußbodenaufbaus definiert die Darstellung
