### ISSUE TITLE
Erweiterung der Klassifizierung vom Raumstempel  (Bodenbeläge)

### ISSUE THREAD

**Issue by WA-NS** [chb-mort/Charlotte-Standard#22]
![Klassifizierung Neue Bodenbeläge](https://user-images.githubusercontent.com/90264298/135249894-1c502a53-92e5-454c-962f-fbd28ced89f4.PNG)

Für die Klassifizierung des Raumstempels haben wir zusätzliche Bodenbeläge hinzugefügt.
Bitte fügen Sie diese in das Template ein.

![Klassifizierung Raumstempel Neue Bodenbeläge](https://user-images.githubusercontent.com/90264298/135251056-da33a16f-636c-4610-9329-9f7fa2d27f06.PNG)

**Comment by WA-NS** [comment]
Wir haben noch für den Fußbodenbelag  Steinplatten hinzugefügt

**Comment by chb-mort** [comment]
sind hinzugefügt
