### ISSUE TITLE
Erweiterung der Klassifizierung vom Fußbodenaufbau 

### ISSUE THREAD

**Issue by WA-NS** [chb-mort/Charlotte-Standard#24]
![Klassifizierung für die decke  Bodenbeläge](https://user-images.githubusercontent.com/90264298/135252257-b5704830-31f9-4c2a-b1fa-63c89c191bba.PNG)
 
Wir konnten im Fußbodenaufbau kein Material definieren, weshalb wir den Bodenbelag in der Klassifizierung hinzugefügt haben. 

Bitte pflegen Sie diese in das Template ein.

![Klassifizierung für die decke  Bodenbeläge Difinieren](https://user-images.githubusercontent.com/90264298/135252898-f6b7529e-ac2c-4245-be53-8888037e3ac0.PNG)

**Comment by chb-mort** [comment]
Bitte im Fußbodenaufbau auch kein Material definieren!
Wie am Telefon besprochen ist die **Definition des Bodenbelags Teil des Raumstempels**, 
allein die Darstellung wird über den Fußbodenbelag definiert.

So ist z.B. im Bad, auch wenn es einen bodengleiche Dusche mit anderen Fliesen gibt, der Bodenbelag trotzdem Fliesen.
In Sonderfällen kann eine Textbeschreibung sinnvoll sein, bzw. eine Mehrfachnennung im Raumstempel.

Die Klassifizierung im Fußbodenaufbau also bitte nicht angeben.
Eine Erklärung wird dem Release beigefügt.
