### ISSUE TITLE
Etikett Für die Tür mit Oberlicht

### ISSUE THREAD

**Issue by WA-NS** [chb-mort/Charlotte-Standard#25]
![Tür mit Oberlicht Etikett neue Klassifizierung](https://user-images.githubusercontent.com/90264298/135263269-878bc527-06eb-471b-9c49-9187b2e35806.PNG)

Wir haben in der Klassifizierung der Tür mit  (Tür mit Oberlicht) ein Zweig hinzugefügt, welchen wir als Etikett für die Tür benutzen können.

Bitte pflegen Sie diesen in das Template ein.

**Comment by chb-mort** [comment]
Wenn ich es richtig verstanden habe, muss also nur die Klassifizierung eingetragen werden?
Das Etikett zur Anzeige der Klassifizierung bleibt ja dasselbe, oder?

**Comment by WA-NS** [comment]
Ja es bleibt

**Comment by chb-mort** [comment]
eingetragen
