### ISSUE TITLE
Template Version

### ISSUE THREAD

**Issue by ws-pschulze** [chb-mort/Charlotte-Standard#4]
Hallöchen, 

aktuell haben wir nur die Chance in Archicad 24 zu arbeiten. 

Könnt ihr bitte das Template von 25 auf 24 abspeichern und nochmals hochladen?

Vielen Dank!

**Comment by chb-mort** [comment]
Laut Mail vom 30. August nutzen Sie nun Archicad 25. Damit wird das Issue geschlossen.
