### ISSUE TITLE
Layout CHB_A4_hoch - Autotext fehlt im Feld "Inhalt"

### ISSUE THREAD

**Issue by ws-pschulze** [chb-mort/Charlotte-Standard#5]
Hallöchen,

beim CHB_A4-hoch/CHB-A3-quer fehlt der Autotext und/oder die Geschossigkeit.

![Problem](https://user-images.githubusercontent.com/88710214/131362670-4944e49b-62b3-4e1c-b430-f89cf7639d14.JPG)

**Comment by chb-mort** [comment]
wird aktualisiert zum nächsten Release.
Bis dahin bitte einfach weiterzeichnen und händisch eintragen wie zuvor.

**Comment by chb-mort** [comment]
eingetragen
