### ISSUE TITLE
Änderung des Template 

### ISSUE THREAD

**Issue by WA-NS** [chb-mort/Charlotte-Standard#9]
Grafische Überschreibung  Neue Ebene mit Vermietung hinzugefügt

- [ ] Maßstab Autotext geändert 

- [ ] Geschosse Autotext Hinzugefügt

- [ ] Heizleitungen in Linien geändert

**Comment by WA-NS** [comment]
- [ ]

**Comment by ws-pschulze** [comment]
- [ ] Klassifizierung "Ablauf/Abschieber" in "**Ablauf**" geändert
- [ ] Klassifizierung "Rohr" in "**Regenrohr**" geändert
- [ ] Vermieter Grundriss Ebenenkombination angepasst: 
            - [ ] Raumstempel aus
            - [ ] Allgemeine Bemaßung aus

- [ ] Modelldarstellung für Vermieter ohne Fensterstempel und ohne Türzarge
- [ ] Modelldarstellung für Technik mit Fensterstempel und Türzarge

**Comment by chb-mort** [comment]
`- [ ] Raumstempel aus`
Bitte Raumstempel **nicht** mit der Ebenenkombination ausstellen und auch **nicht** die Raumbezeichnung über ein neues Textelement lösen.
Die Raumstempel im Template sind im M1:100 nur die Raumbezeichnung.
Im Pflichtenheft wie auch in der Beispieldatei ist beschrieben wie die Bezeichnung maßstabsabhängig verschoben werden kann.
